web:
  - https://www.maharaniweddings.com/
  - https://www.maharaniweddings.com/gallery
  - https://www.maharaniweddings.com/indian-wedding-vendors
  - https://www.maharaniweddings.com/certified-indian-wedding-vendors
social:
  - https://www.instagram.com/maharaniweddings
  - https://www.pinterest.com/maharaniwedding/
  - https://www.facebook.com/MaharaniWeddings/
